### ISSUE TITLE
route53 provider 'record replace' doesn't actually replace

### ISSUE THREAD

**Issue by jbouse** [Netflix/denominator#257]
If you attempt to use the 'replace' method for record entries it does not actually update/replace the entry but instead errors out saying that the record already exists. Either replace should be removed and force the 'add' and 'delete' functions or it should be updated to operate as the documentation would suggest as it reads:

    replace
        creates or replaces data in a record set corresponding to name and
        type. sets ttl, if present

Instead you get:

    ;; error: Route53#changeBatch(String,List) failed with errors [Tried to create resource record set [name='blah.example.com.', type='A'] but it already exists]

**Comment by adriancole** [comment]
crazy latency, but I plan to spend a bit of time in denominator. ping back if you'd still like this addressed!

**Comment by jbouse** [comment]
I'm no longer using denominator myself personally as I've switched jobs but my employer is still utilizing the setup I had in place when I left and this did affect the environment.

**Comment by adriancole** [comment]
confirmed

**Comment by adriancole** [comment]
ok, so what happened here is that the record name was missing the trailing dot. there's possibly a way we can help prevent this, by trying to be more smart.

```bash
# doesn't work
denominator -p route53 ... replace --type A --name foobar.denominator.io -d 1.2.3.5
# works
denominator -p route53 ... replace --type A --name foobar.denominator.io. -d 1.2.3.5
```
