### ISSUE TITLE
denominator giving error when advanced directional dns is not enabled

### ISSUE THREAD

**Issue by AEgitadmin** [Netflix/denominator#259]
I am getting below error from denominator because we don't have advanced directional dns enabled. Is it still possible to use denominator for our account?

[UltraDNS#getDirectionalPoolsOfZone] <--- HTTP/1.1 500 Server Error (1492ms)
;; error: UltraDNS#getDirectionalPoolsOfZone(String) failed with error 4006: Directional feature not Enabled or Directional migration is not done.

**Comment by adriancole** [comment]
crazy latency, but I plan to spend a bit of time in denominator. ping back if you'd still like this addressed!
