### ISSUE TITLE
Dynect - incomplete status response causes IllegalStateException

### ISSUE THREAD

**Issue by clarkbreyman** [Netflix/denominator#261]
Running the CLI with:
denominator -v -p dynect -c REDACTED -c REDACTED -c REDACTED record -z 0.0.5.f.1.1.1.0.1.0.a.2.ip6.arpa list

Returns ";; error: java.lang.IllegalStateException: unknown format: null"

It looks like DynECT's long running job response isn't handled in this case. It's not clear whether the bug is in Denominator or DynECT as their docs seem to indicate that a 307 redirect would be generated. 

[DynECT#rrsets] ---> GET https://api2.dynect.net/REST/AllRecord/0.0.5.f.1.1.1.0.1.0.a.2.ip6.arpa?detail=Y HTTP/1.1
[DynECT#rrsets] API-Version: 3.5.0
[DynECT#rrsets] Content-Type: application/json
[DynECT#rrsets] Auth-Token: REDACTED
[DynECT#rrsets] ---> END HTTP (0-byte body)
[DynECT#rrsets] <--- HTTP/1.1 200 OK (4107ms)
[DynECT#rrsets] Transfer-Encoding: chunked
[DynECT#rrsets] Date: Tue, 24 Jun 2014 23:51:03 GMT
[DynECT#rrsets] Connection: keep-alive
[DynECT#rrsets] Content-Type: application/json
[DynECT#rrsets] Server: nginx/1.2.6
[DynECT#rrsets] 
[DynECT#rrsets] {"status": "incomplete", "data": null, "job_id": 966935380}
[DynECT#rrsets] <--- END HTTP (59-byte body)

**Comment by adriancole** [comment]
crazy latency, but I plan to spend a bit of time in denominator. ping back if you'd still like this addressed!

**Comment by adriancole** [comment]
@clarkbreyman @chrischalstrom can you ping dynect to join denominator-dev google group and/or give me an account to test with? Otherwise, it is likely things like this will happen. https://groups.google.com/forum/#!forum/denominator-dev

**Comment by jwbraucher** [comment]
I can follow-up with our support contact at Dynect and ask them to pass along the message. 

We experienced this bug as recently as November, 2014 before the behavior was addressed in fog (https://github.com/fog/fog/pull/3267). Our team switched from denominator to fog as part of an unrelated effort to integrate our DNS management into another ruby application. Thanks @chrischalstrom for fixing the behavior in fog. That change to fog has resolved the issue for us, so it would seem like it is still a good idea to implement the same workaround in denominator as well.

**Comment by adriancole** [comment]
Great. Thanks.

**Comment by jwbraucher** [comment]
@adriancole, Dynect support responded with the following:
> If they reach out directly to concierge@dyn.com referencing this case and the previous case, we'll see if we can provide an account for testing purposes.

The two cases I've opened previously with concierge@dyn.com are:
Case: 00183061 and Case: 00134709

You are welcome to reference me in your request as well if you like.

**Comment by jwbraucher** [comment]
FWIW - it seems the bug with the Dynect API only occurs when the "detail=Y" query parameter is supplied. If there is a way to modify Denominator to achieve the same goals with Dynect (generally speaking) without using "detail=Y" that might be a better way to address the issue.

I don't know the API well enough to understand the significance of "detail=Y", but as Dynect support has pointed out - it is not an officially documented feature.

**Comment by adriancole** [comment]
detail=Y was added back in the day because the api was falling over due to
too many requests. Without it, automation resulted in Netflix automation
being unable to complete. Basically, detail=Y reduced chattiness, which was
overwhelming the DynECT servers.

https://github.com/Netflix/denominator/pull/164

There was a new api promised, a restful one, which I've no idea whether
that actually happened or not. I also don't know if the workaround has any
impact on service health. Anyway, that's the context, FWIW.

**Comment by adriancole** [comment]
ps I've opened a case w/Dyn about the account. thanks for the help (and fingers crossed)

**Comment by adriancole** [comment]
Looking in depth now.

So denominator already follows redirects. The problem here is that dynect sometimes returns a success code when the response is incomplete. This is terrible behavior. I'm not convinced that this would only occur when `detail=Y`, so I'd rather employ the workaround separately.
