### ISSUE TITLE
error: status 406 Not Acceptable on RS Cloud DNS

### ISSUE THREAD

**Issue by quinncomendant** [Netflix/denominator#262]
I'm using Denominator 4.3.3, Java version: 1.6.0_65, on OS X 10.9.5 (installed via HomeBrew). I'm trying to use the Rackspace Cloud DNS provider, and have added my API credentials to `~/.denominatorconfig` as per the instructions:

    name: clouddns-strangecode
    provider: clouddns
    credentials:
        username: xxxxxx
        apiKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

WHen I run `zone list` (or any other commands), I get a `HTTP/1.1 406 Not Acceptable` error:

    [q ~] denominator -n clouddns-strangecode zone list
    [CloudIdentity#apiKeyAuth] ---> POST https://identity.api.rackspacecloud.com/v2.0/tokens HTTP/1.1
    [CloudIdentity#apiKeyAuth] <--- HTTP/1.1 200 OK (13834ms)
    [CloudDNS#domains] ---> GET https://dns.api.rackspacecloud.com/v1.0/721416/domains HTTP/1.1
    [CloudDNS#domains] <--- HTTP/1.1 406 Not Acceptable (4569ms)
    ;; error: status 406 reading CloudDNS#domains()

With verbose output:

    [q ~] denominator -v -n clouddns-strangecode zone list
    [CloudIdentity#apiKeyAuth] ---> POST https://identity.api.rackspacecloud.com/v2.0/tokens HTTP/1.1
    [CloudIdentity#apiKeyAuth] Content-Type: application/json
    [CloudIdentity#apiKeyAuth] Content-Length: 111
    [CloudIdentity#apiKeyAuth] 
    [CloudIdentity#apiKeyAuth] {"auth":{"RAX-KSKEY:apiKeyCredentials":{"username":"abc","apiKey":"xxxxxxxxxxxxxxxx"}}}
    [CloudIdentity#apiKeyAuth] ---> END HTTP (111-byte body)
    [CloudIdentity#apiKeyAuth] <--- HTTP/1.1 200 OK (3587ms)
    [CloudIdentity#apiKeyAuth] Date: Sun, 05 Oct 2014 14:57:39 GMT
    [CloudIdentity#apiKeyAuth] Transfer-Encoding: chunked
    [CloudIdentity#apiKeyAuth] X-NewRelic-App-Data: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
    [CloudIdentity#apiKeyAuth] Front-End-Https: on
    [CloudIdentity#apiKeyAuth] Content-Type: application/json
    [CloudIdentity#apiKeyAuth] Connection: keep-alive
    [CloudIdentity#apiKeyAuth] Server: nginx
    [CloudIdentity#apiKeyAuth] vary: Accept, Accept-Encoding, X-Auth-Token
    [CloudIdentity#apiKeyAuth] 
    [CloudIdentity#apiKeyAuth] {"access":{"token":{xxxxxxxxxxxxxxxx}}}
    [CloudIdentity#apiKeyAuth] <--- END HTTP (11720-byte body)
    [CloudDNS#domains] ---> GET https://dns.api.rackspacecloud.com/v1.0/721416/domains HTTP/1.1
    [CloudDNS#domains] X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxx
    [CloudDNS#domains] ---> END HTTP (0-byte body)
    [CloudDNS#domains] <--- HTTP/1.1 406 Not Acceptable (1568ms)
    [CloudDNS#domains] x-api-version: 1.0.33
    [CloudDNS#domains] Date: Sun, 05 Oct 2014 14:57:42 GMT
    [CloudDNS#domains] Content-Length: 0
    [CloudDNS#domains] x-newrelic-app-data: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    [CloudDNS#domains] Via: 1.1 Repose (Repose/2.13.2)
    [CloudDNS#domains] Content-Type: application/json
    [CloudDNS#domains] Server: Jetty(8.0.y.z-SNAPSHOT)
    ;; error: status 406 reading CloudDNS#domains()

**Comment by adriancole** [comment]
crazy latency, but I plan to spend a bit of time in denominator. ping back if you'd still like this addressed!

**Comment by adriancole** [comment]
via feign update, this will be fixed in 4.4
