### ISSUE TITLE
cli add record does not include new record with new rdata when rrset has old data. 

### ISSUE THREAD

**Issue by hasika** [Netflix/denominator#269]
denominator-cli ResourceRecordSetCommands class' add command filters out new data. 

Line 261-
 
ImmutableList<Map<String, Object>> newRData =
                        		ImmutableList.copyOf(filter(rrset.records(), not(in(toAdd.records()))));

Fix - 
                      
ImmutableList<Map<String, Object>> newRData =
                                ImmutableList.copyOf(filter(toAdd.records(), not(in(rrset.records()))));

**Comment by adriancole** [comment]
crazy latency, but I plan to spend a bit of time in denominator. ping back if you'd still like this addressed!
