### ISSUE TITLE
build no longer creates cli/build/denominator

### ISSUE THREAD

**Issue by adriancole** [Netflix/denominator#272]
Before switching to the latest nebula, executing `./gradlew clean test install` from the root of your denominator clone would create `cli/build/denominator`

This was due to an entry at the bottom of the cli's build.gradle
```
artifacts {
  archives fatJar
}
```

I noticed this is no longer being created. Any ideas?

**Comment by rspieldenner** [comment]
Does it absolutely have to be an executable jar? I'd usually go with the 'application' plugin to do this type of thing http://gradle.org/docs/current/userguide/application_plugin.html

Otherwise I'll take a look Monday.

**Comment by adriancole** [comment]
there's a fair amount of denominator cli users who see it as an executable.
I can also look into the gradles if you get stuck.. just I'm usually not
that good at it.

**Comment by rspieldenner** [comment]
When I do `./gradlew clean build install` I get a cli/build/denominator

**Comment by adriancole** [comment]
oh well that's interesting! maybe there's a subtle thing when one puts "test" instead of "build" now. I don't mind the incantation so long as the release scripts create this..

**Comment by adriancole** [comment]
No action needed.. I'll just update the README!

**Comment by rspieldenner** [comment]
actually thought about it some more. And pull request does it the old way.

**Comment by adriancole** [comment]
Great. This helps, Rob.
