### ISSUE TITLE
Map Credentials does not work some times

### ISSUE THREAD

**Issue by santhosh-tekuri** [Netflix/denominator#280]
`MapCredenitals` are converted to `List<Object>` by providers using:

````java
ListCredentials.asList(credentials)
````
current implementation of this method, simply takes returns `new ArrayList<Object>(map.values())`

note that, in map order of entries is not defined. so credential parameters might be in wrong order;

you can verify the same by following test:
````java
        Map<String, String> map = new LinkedHashMap<String, String>();
        map.put("secretKey", "ZZZZZZZZZZZZZZ");
        map.put("accessKey", "AAAAAA");

        System.out.println(map.values());
        Credentials credentials = Credentials.MapCredentials.from(map);
        DNSApiManager manager = Denominator.create("route53", CredentialsConfiguration.credentials(credentials));
        ZoneApi zones = manager.api().zones();
        for(Zone zone: zones)
            System.out.println(zone);
````
the above code fails to list zones. but if `accessKey` is inserted before `secretKey`, then it works

I fixed the issue in my fork branch `map-credentials`:
https://github.com/santhosh-tekuri/denominator/tree/map-credentials

please evaluate the fix and merge

**Comment by adriancole** [comment]
@santhosh-tekuri I understand what you are doing, I hadn't run into this as we used deterministic order maps and issued put in the right order. I agree that this could be a problem.

I looked at your pull request and it is a lot of code and also api breaking to fix `ListCredentials.asList`. I think there are two viable ways out.

1. Enhance javadoc of `MapCredentials.from` to highlight the input map must be a deterministically ordered map, and that entries in that map should iterate in the same order as credentials configuration. The simplest way is to use a LinkedHashMap and do the put commands in the correct order.
2. Deprecate and change code to stop using `ListCredentials.asList`, raising a later issue to remove it.

Thoughts?

**Comment by adriancole** [comment]
also, if javadocing, probably best to say insertion order, other sorts would be confusing.

**Comment by santhosh-tekuri** [comment]
In my case, i get credentials in json format. which is read into Map.
for route53 it works fine. but for dynect it failed. after digging into source, i found the issue.

my suggestion will be, do two steps:
1. Deprecate and stop using `ListCredentials.asList`
2. add `MapCredentials.asMap` and use it where `ListCredentials.asList` is used. it is more easier and intuitive to convert list credentials to map credentials.

If you are satisfied by my suggestion, I can submit a pull request for this change

**Comment by adriancole** [comment]
Part one makes sense. I don't think that the second part is needed. The
only use case for credential conversion is in provider code.

When a list is present, the implementation could easily use it. In other
words, instead of adding another utility and forcing more conversions that
allocate new objects, let's just test Map vs List in the providers
themselves.

**Comment by santhosh-tekuri** [comment]
My concern is as a user I am forced to use following workaround in my code:

```java
    public static denominator.Credentials getCredentials(Map<String, String> credentialsMap, String provider){
        Provider provider = Providers.getByName(provider);
        Map<String, Collection<String>> stringCollectionMap = provider.credentialTypeToParameterNames();
        for(Collection<String> c: stringCollectionMap.values()){
            Map<String, String> map = new LinkedHashMap<>();
            for(String param: c){
                String value = credentialsMap.get(param);
                if(value==null)
                    break;
                map.put(param, value);
            }
            if(c.size()==map.size())
                return denominator.Credentials.MapCredentials.from(map);
        }
        return Credentials.AnonymousCredentials.INSTANCE;
    }
```
and i can't enforce users, to provide credentials in json in correct order.

**Comment by adriancole** [comment]
I agree we don't want people to have to guard this. What I am suggesting is
that we change the provider code to not be sensitive to the order of the
map.

When we deprecate and stop using ListCredentials.asList, we will end up
with three supported scenarios. Either the Credentials object is an
instance of List, Map, or anonymous. The provider code for list will be
exactly as it was before. Each provider will need to add logic to extract
keys by name when credentials is an instanceof Map.

Make sense? I will send an example shortly for how to change Route53

**Comment by adriancole** [comment]
Here's an example. Note that it seems route53 still has wrong formatting, so I will raise a PR in a minute to correct.

```
-        List<Object> creds = ListCredentials.asList(currentCreds);
-        String accessKey = creds.get(0).toString();
-        String secretKey = creds.get(1).toString();
-        String token = null;
-        if (creds.size() == 3)
-            token = creds.get(2).toString();
+        String accessKey;
+        String secretKey;
+        String token;
+        if (currentCreds instanceof List) {
+            List<Object> creds = (List<Object>) currentCreds;
+            accessKey = creds.get(0).toString();
+            secretKey = creds.get(1).toString();
+            token = creds.size() == 3 ? creds.get(2).toString() : null;
+        } else if (currentCreds instanceof Map) {
+            Map<String, Object> creds = (Map<String, Object>) currentCreds;
+            accessKey = checkNotNull(creds.get("accessKey"), "accessKey").toString();
+            secretKey = checkNotNull(creds.get("secretKey"), "secretKey").toString();
+            token = creds.containsKey("sessionToken") ? creds.get("sessionToken").toString() : null;
+        } else {
+            throw new IllegalArgumentException("Unsupported credential type: " + currentCreds);
+        
```

This does cost a few lines per provider, but the lack of indirection makes the contract clear. It also avoids duplicating objects or needlessly converting them.

**Comment by santhosh-tekuri** [comment]
the change looks good, as you said adds few lines per provider

**Comment by adriancole** [comment]
ps will merge #284 momentarily, which should help avoid you needing to do an ugly rebase.
