### ISSUE TITLE
Release 4.4

### ISSUE THREAD

**Issue by adriancole** [Netflix/denominator#306]
We are readying for a long overdue update of denominator.

Current Progress:
- [x] Make sure all issues are closed out or bumped
- [x] Live test all providers
- [x] Make `cli/build/denominator providers` makes sense when built from the `4.x` branch 
- [x] update README.md and denominator-cli/README.md
- [x] release `4.4.1` from `4.x` branch, publishing to maven central
- [x] Update the [homebrew formula](https://github.com/mxcl/homebrew/pulls) with the latest [bintray content](https://bintray.com/artifact/download/netflixoss/maven/com/netflix/denominator/denominator-cli/4.4.1/denominator-cli-4.4.1-fat.jar)
- [x] verify that 4.4.1 is in [maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.netflix.denominator%22%20AND%20a%3A%22denominator-core%22)
- [x] Update android example to 4.4.1
- [x] communicate via irc, google groups, twitter etc.

Test results:

| Provider  | Test Status | Parameters | Notes |
| ------------- | ------------- | ------------- | ------------- |
| clouddns | pass  | -Dclouddns.username=xxxx -Dclouddns.apiKey=xxxx -Dclouddns.zone=denominator.com |  |
| designate | pass  | -Ddesignate.url=https://region-a.geo-1.identity.hpcloudsvc.com:35357/v2.0/ -Ddesignate.tenantId=xxxx -Ddesignate.username=xxxx -Ddesignate.password=xxxx -Ddesignate.zone=denominator.io. | |
| dynect | pass  | -Ddynect.customer=Netflix-denom -Ddynect.username=xxxx -Ddynect.password=xxxx -Ddynect.zone=denominator2.io | |
| route53 | pass  | -Droute53.accessKey=xxxx -Droute53.secretKey=xxxx -Droute53.zone=denominator.io. |  |
| ultradns | pass  | -Dultradns.username=xxxx -Dultradns.password=xxxx -Dultradns.zone=denominator.io. | |

**Comment by adriancole** [comment]
@rspieldenner ETA for release is early next week. As this hasn't been released in a while, can check and see there's no blockers (ex. libraries not whitelisted, etc).

**Comment by adriancole** [comment]
@rspieldenner all code needed for 4.4 is in the 4.x branch. Can you cut 4.4.0 from 4.x at next opportunity?

**Comment by rspieldenner** [comment]
do you want to get feign 8.0.0 in here?

**Comment by adriancole** [comment]
nah. we can do feign 8 (#326) in denominator 4.5 (among other things).
thanks for asking!

**Comment by rspieldenner** [comment]
4.4.0 on bintray. Will be synced to mavenCentral sometime soon

**Comment by adriancole** [comment]
homebrew bump https://github.com/Homebrew/homebrew/pull/37536

**Comment by adriancole** [comment]
maven central in sync. just waiting for homebrew merge

**Comment by adriancole** [comment]
Whoops. missed a spot unhooking discoverydns 044fe5e4e7596e5148f33a0579405209fb79c6a9

This made the homebrew test fail

@rspieldenner can you cut 4.4.1 from 4.x branch?

**Comment by adriancole** [comment]
added a step to the checklist that will prevent this problem from surfacing again

**Comment by adriancole** [comment]
bumped homebrew to 4.4.1

**Comment by adriancole** [comment]
announced. lazy executing android sample update
