### ISSUE TITLE
Publish test jars

### ISSUE THREAD

**Issue by adriancole** [Netflix/denominator#343]
We should publish test jars so that it is easier for third-party denominator providers to test their code. Specifically, we need test jars published to maven for the `model` and `core` modules.

**Comment by adriancole** [comment]
cc @MisterK

**Comment by rspieldenner** [comment]
You can add apply plugin: 'nebula-test-jar' to any project's build.gradle
that needs to produce a test jar. Alternatively just split out testing
chunks to separate subprojects.

**Comment by adriancole** [comment]
heh thanks tons.. I had significantly more lines in progress than that one!

**Comment by MisterK** [comment]
@adriancole Sorry but I cannot find the test jars in Maven Central for v4.5. Are you planning on releasing them over there as well? Or do I have to build them myself?
Thanks in advance.

**Comment by adriancole** [comment]
You shouldn't have to build your own test jars. We need to look into this.

**Comment by adriancole** [comment]
@MisterK sorry. I missed a cherry-pick. pushing 4.5.1

https://travis-ci.org/Netflix/denominator/builds/59734605

**Comment by MisterK** [comment]
@adriancole Thanks! I'm now all set to finish integrating with 4.5.1.
