### ISSUE TITLE
Seems like travis is having a hard time downloading gradle

### ISSUE THREAD

**Issue by adriancole** [Netflix/denominator#353]
Seems like travis is having a hard time downloading gradle.. am I interpreting this right?

https://travis-ci.org/Netflix/denominator/builds/56234806

```
144.46s$ ./installViaTravis.sh
Assemble Branch with Snapshot => Branch [adrian.zone-ttl-email]
Downloading https://services.gradle.org/distributions/gradle-2.2.1-bin.zip
--snip--
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'denominator'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Artifact 'xbean-reflect.jar (org.apache.xbean:xbean-reflect:3.4)' not found.
     Searched in the following locations:
         https://jcenter.bintray.com/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar

```

**Comment by adriancole** [comment]
Looks like the jar went missing!

https://jcenter.bintray.com/org/apache/xbean/xbean-reflect/3.4/

**Comment by adriancole** [comment]
tweeted to bintray, just in case that somehow works.  https://twitter.com/adrianfcole/status/581899588120010752

**Comment by rspieldenner** [comment]
I'm away from computer until Tuesday. @quidryan could you have a look. We might need to change a plugin dependency

**Comment by adriancole** [comment]
I think we're back in business per the tweet. Validating with another PR.

**Comment by adriancole** [comment]
yep. back in business
