### ISSUE TITLE
WriteLiveTest- Quotation wrapping of TXT rdata

### ISSUE THREAD

**Issue by sanjaympawar1** [Netflix/denominator#362]
WriteLiveTest failling due to exact match of TXT rdata where Verisign MDNS is wrapping TXT rdata in double quotes.
TXT record data comparison is performed as exact match.  However some DNS system may wrap TXT data within double quotes.
The TXT record data wrapping by quotes is prescribed in RFC-1035 (http://tools.ietf.org/html/rfc1035) section 3.3.14 and definition of "<character-string>"
at page #34

**Comment by adriancole** [comment]
consolidating into #361
