### ISSUE TITLE
Breaking API change at Rackspace CloudDNS

### ISSUE THREAD

**Issue by quinncomendant** [Netflix/denominator#381]
Denominator has stopped working with Rackspace Cloud DNS because requests to its API at `/domains/XXXXX/records?name=example.com&type=SOA` fail with a code 404 error (resulting verbose output below). 

I submitted a ticket to Rackspace Cloud DNS and they confirmed (via their DNS team) that, "a new version of the API was released" on January 10, 2019. They claim that the Cloud DNS API does not, *and never did*, support SOA type queries. 🤔 However, it seems likely that the Jan 10 API change has broken denominator, since I can confirm it was working on January 5, and was broken by January 13.

Is it possible denominator was using an undocumented feature of the Cloud DNS API?

I know this project hasn't been active for a few years. Is there any chance it will be updated to support Cloud DNS again?

Thanks!

    [CloudDNS#recordsByNameAndType] ---> GET https://dns.api.rackspacecloud.com/v1.0/721416/domains/4445712/records?name=pulso.io&type=SOA HTTP/1.1
    [CloudDNS#recordsByNameAndType] X-Auth-Token: […]
    [CloudDNS#recordsByNameAndType] ---> END HTTP (0-byte body)
    [CloudDNS#recordsByNameAndType] <--- HTTP/1.1 404 Not Found (22ms)
    [CloudDNS#recordsByNameAndType] Set-Cookie: […]; path=/; HttpOnly; Secure
    [CloudDNS#recordsByNameAndType] Content-Length: 14
    [CloudDNS#recordsByNameAndType] X-Trans-Id: […]
    [CloudDNS#recordsByNameAndType] Date: Fri, 18 Jan 2019 19:42:38 GMT
    [CloudDNS#recordsByNameAndType] Date: Fri, 18 Jan 2019 19:42:38 GMT
    [CloudDNS#recordsByNameAndType] Via: 1.1 Repose (Repose/8.9.1.0)
    [CloudDNS#recordsByNameAndType] Content-Type: application/json;charset=utf-8
    [CloudDNS#recordsByNameAndType]
    [CloudDNS#recordsByNameAndType] {"records":[]}
    [CloudDNS#recordsByNameAndType] <--- END HTTP (14-byte body)
    ;; error: status 404 reading CloudDNS#recordsByNameAndType(int,String,String); content:
    {"records":[]}

**Comment by onerackofdns** [comment]
I've added a workaround to allow the undocumented type=SOA queries, which should fix this issue.

**Comment by quinncomendant** [comment]
Hey @onerackofdns! Your fix to the Rackspace Cloud DNS API has allowed denominator to work again. Thanks!
